apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=359145461483.dkr.ecr.ap-southeast-1.amazonaws.com/my-ecr-repo-devops/frontend:*
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: 359145461483.dkr.ecr.ap-southeast-1.amazonaws.com/my-ecr-repo-devops/frontend
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
