apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: eks-dev-argo-frontend
    newName: 359145461483.dkr.ecr.ap-southeast-1.amazonaws.com/my-ecr-repo-devops/frontend
    newTag: 'latest'
resources:
  - _deployment.yaml
  - _service.yaml
