apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    argocd-image-updater.argoproj.io/image-list: myalias=359145461483.dkr.ecr.ap-southeast-1.amazonaws.com/my-ecr-repo-devops/frontend:*
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  type: ClusterIP
